### ISSUE TITLE
Incremental build

### ISSUE THREAD

**Issue by TrySound** [Kflash/karma-rollup-plugin#2]
Since one of the last releases rollup introduced `cache` option which accepts previously built bundle and contain transformed content and maps.

``` js
let cache = null;

rollup.rollup({
  entry: '...',
  plugins: [buble()],
  cache
}).then(bundle => {
  cache = bundle;
});

rollup.rollup({
  entry: '...',
  plugins: [buble()],
  cache // contains buble transformations
}).then(bundle => {
  cache = bundle;
});
```

**Comment by ghost** [comment]
@TrySound Not 100% sure if I understood you right here, but added the above code to the source.

**Comment by TrySound** [comment]
It's about watching iterations. In your code `cache` is always `null`.

**Comment by ghost** [comment]
OK.  I'm driving atm. I will look into it later if you don't solve it.

**Comment by ghost** [comment]
@TrySound Can you fix this?  I also looked deeper into touchParents and changeParents. And agree it's buggy, but it seems that this is related to Rollup core. Nothing to do with Karma itself.

I also looked at other preprocessors, and no one seems to have issue like this?

And as it is now, this only works for tests or files in the files: [] in Karma config. The source files in /src will not change. E.g. you write a new test for some source code changes you did while the watch task is running. I guess the tests will break, becaue the new source file in the /src will not be loaded?

This one is an issue because if we try to use Istanbul etc. and attached the source files in the files[] section in karma.conf.js, Istanbul will start to work strange.

Up for any ideas how to solve this?

**Comment by TrySound** [comment]
@Kflash Let's just leave this optimisation for a time. Need to make more stable preprocessor

**Comment by ghost** [comment]
OK.  BTW.  Can you merge your latest PR?

**Comment by ghost** [comment]
@TrySound I think this can be tricky to implement. After a deep study of the rollup code base I think we put this on hold for now. During my study I discovered potential memory leaks issues, depots,  performance  killers, and a bunch of other things. I counted it to be around 37 issues. 

So just wait for a stable rollup release.

**Comment by ghost** [comment]
@TrySound I guess this isn't a case anymore. So closing. Re-open if you got a fix.
